=== jcayzac/random-stuff/xmls/xmls/Directory.dtd
<!ELEMENT Directory (Directory*,File*,Link*,Socket*,CharacterDevice*,BlockDevice*,Fifo*)>
	<!ATTLIST Directory path CDATA #IMPLIED>
	<!ATTLIST Directory name CDATA #REQUIRED>
<!ELEMENT File EMPTY>
	<!ATTLIST File name CDATA #REQUIRED>
	<!ATTLIST File size CDATA #REQUIRED>
	<!ATTLIST File type CDATA #IMPLIED>
<!ELEMENT Link EMPTY>
	<!ATTLIST Link name CDATA #REQUIRED>
	<!ATTLIST Link target CDATA #IMPLIED>
<!ELEMENT Socket EMPTY>
	<!ATTLIST Socket name CDATA #REQUIRED>
<!ELEMENT CharacterDevice EMPTY>
	<!ATTLIST CharacterDevice name CDATA #REQUIRED>
<!ELEMENT BlockDevice EMPTY>
	<!ATTLIST BlockDevice name CDATA #REQUIRED>
<!ELEMENT Fifo EMPTY>
	<!ATTLIST Fifo name CDATA #REQUIRED>

=== jcayzac/random-stuff/xmls/xmls/example2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<?xml-stylesheet type="text/xsl" href="http://www.brainlex.com/XSLT/Directory.xsl"?>
<!DOCTYPE Directory SYSTEM "http://www.brainlex.com/DTD/Directory.dtd">
<Directory path="/home/deepmind/Experiments/xmls" name="xmls">
	<File name="blééééééééé" size="0" />
	<File name="Directory.xsl" size="2700" />
	<File name="1992" size="1340" />
	<File name="xmls.cxx" size="13135" />
	<File name="example1.xml" size="388" />
	<File name="example2.xml" size="0" />
	<File name="Directory.dtd" size="690" />
	<File name="xmls" size="30774" />
	<File name="example.xml" size="438" />
	<File name="Other.xsl" size="1538" />
</Directory>
